version: '2'

services:
  backend:
    build: .
    ports:
      - '8080:8080'
      - '9229:9229' # debugging port
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:docker
    environment:
      NODE_ENV: development
      PORT: 8080
